import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Script from 'next/script'
//import { ThemeProvider } from "@/app/theme-provider";
import { MobMnuBtns } from "@/widgets/MobMnuBtns/ui/MobMnuBtns";
import { Coockie } from "@/features/coockie";
import { FooterWidget } from "@/widgets/footer";



const Gilroy = localFont({
  src: [
     {
      path: "/fonts/gilroy/Gilroy-Light.ttf",
      weight: '300',
      style: 'normal'
    },
    {
      path: "/fonts/gilroy/Gilroy-Regular.ttf",
      weight: '400',
      style: 'normal'
    },
    {
      path: "/fonts/gilroy/Gilroy-Medium.ttf",
      weight: '500',
      style: 'normal'
    },
    {
      path: "/fonts/gilroy/Gilroy-SemiBold.ttf",
      weight: '600',
      style: 'normal'
    },
  ],
   display: 'swap'
})

export const metadata: Metadata = {
  title: "Drivovo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
       <head>
        {/* Скрипт для установки темы до гидрации */}
        <Script id="theme-init" strategy="beforeInteractive">
          {`
            (function() {
              try {
                const theme = localStorage.getItem('app-theme');
                if (theme === 'dark') {
                  document.documentElement.classList.add('dark');
                } else {
                  document.documentElement.classList.remove('dark');
                }
              } catch (e) {}
            })();
          `}
        </Script>
      </head>

      <body className={`${Gilroy.className}  antialiased dark:bg-[#030303]`} >
        
            {children}
             
            <FooterWidget />
       
          <MobMnuBtns />
          <Coockie />
      </body>
    </html>
  );
}
